@startuml
class miembro
miembro <-- boardmember
persona <-- miembro

class boardmember
boardmember -- boardmeeting
class Evento
Evento -- miembro
Evento <-- Conferencia
class Conferencia
Conferencia -- persona
class boardmeeting
boardmeeting --> Evento
class localizacion
localizacion -- Evento
class persona
class aauoc
aauoc o-- localizacion
aauoc o-- persona
aauoc o-- Evento
@enduml